<?php
/**
 * Copyright 2025 DPD France S.A.S.
 *
 * This file is a part of dpdfrance module for Prestashop.
 *
 * NOTICE OF LICENSE
 *
 * This file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for
 * your needs please contact us at support.ecommerce@dpd.fr.
 *
 * @author    DPD France S.A.S. <support.ecommerce@dpd.fr>
 * @copyright 2025 DPD France S.A.S.
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
if (!defined('_PS_VERSION_')) {
    exit;
}

/**
 * @return bool
 * @throws PrestaShopDatabaseException
 */
function upgrade_module_6_3_0()
{
    // Creation de la table de stockage des méthodes de paiements liées au marketplace
    $sqlRelaisStorage = '
            CREATE TABLE IF NOT EXISTS `' . _DB_PREFIX_ . 'dpdfrance_marketplace` (
            `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
            `payment_method` VARCHAR(255) NOT NULL,
            `active` TINYINT(1) NOT NULL,
            PRIMARY KEY (`id`)
            ) ENGINE=' . _MYSQL_ENGINE_ . ' DEFAULT CHARSET=utf8';

    return Db::getInstance()->execute($sqlRelaisStorage);
}
