<?php
/**
 * Copyright 2025 DPD France S.A.S.
 *
 * This file is a part of dpdfrance module for Prestashop.
 *
 * NOTICE OF LICENSE
 *
 * This file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for
 * your needs please contact us at support.ecommerce@dpd.fr.
 *
 * @author    DPD France S.A.S. <support.ecommerce@dpd.fr>
 * @copyright 2025 DPD France S.A.S.
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
if (!defined('_PS_VERSION_')) {
    exit;
}

use PrestaShop\Module\DPDFrance\Util\DPDCompliancy;
use PrestaShop\Module\DPDFrance\Util\DPDLogs;

/**
 * @param DPDFrance $module
 * @return bool
 */
function upgrade_module_6_4_2($module)
{
    // Creation de la table dpdfrance_module_logs
    $sqlDPDModuleLogs = '
            CREATE TABLE IF NOT EXISTS `' . _DB_PREFIX_ . 'dpdfrance_module_logs` (
            `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
            `datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            `dpdfrance_module_version` VARCHAR(10) NOT NULL,
            `prestashop_version` VARCHAR(10) NOT NULL,
            PRIMARY KEY (`id`)
            ) ENGINE=' . _MYSQL_ENGINE_ . ' DEFAULT CHARSET=utf8';

    if (!Db::getInstance()->Execute($sqlDPDModuleLogs)) {
        return false;
    }

    // Creation de la table dpdfrance_full_logs
    $sqlDPDFullLogs = '
            CREATE TABLE IF NOT EXISTS `' . _DB_PREFIX_ . 'dpdfrance_full_logs` (
            `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
            `datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            `id_dpdfrance_module_logs` INT(10) NOT NULL,
            `param_name` VARCHAR(255) NOT NULL,
            `old_param_value` VARCHAR(255),
            `new_param_value` VARCHAR(255),
            PRIMARY KEY (`id`)
            ) ENGINE=' . _MYSQL_ENGINE_ . ' DEFAULT CHARSET=utf8';

    if (!Db::getInstance()->Execute($sqlDPDFullLogs)) {
        return false;
    }

    try {
        DPDLogs::getLastLog();
        DPDLogs::checkVersion();
    } catch (Exception $e) {
        return false;
    }

    if (DPDCompliancy::isMyPrestashopVersion('>', '8.0.0')) {
        return $module->registerHook('actionFilterDeliveryOptionList');
    }

    return true;
}
