<?php
/**
 * Copyright 2024 DPD France S.A.S.
 *
 * This file is a part of dpdfrance module for Prestashop.
 *
 * NOTICE OF LICENSE
 *
 * This file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for
 * your needs please contact us at support.ecommerce@dpd.fr.
 *
 * @author    DPD France S.A.S. <support.ecommerce@dpd.fr>
 * @copyright 2024 DPD France S.A.S.
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
if (!defined('_PS_VERSION_')) {
    exit;
}

/**
 * @return bool
 * @throws PrestaShopDatabaseException
 */
function upgrade_module_6_3_2()
{
    // Suppression des anciens fichiers devenus obsolètes ou déplacés
    Tools::deleteFile(_PS_MODULE_DIR_ . 'dpdfrance/ajax.php');
    Tools::deleteFile(_PS_MODULE_DIR_ . 'dpdfrance/cron.php');
    Tools::deleteFile(_PS_MODULE_DIR_ . 'dpdfrance/pdf/.htaccess');

    return true;
}
