{**
 * Copyright 2025 DPD France S.A.S.
 *
 * This file is a part of dpdfrance module for Prestashop.
 *
 * NOTICE OF LICENSE
 *
 * This file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for
 * your needs please contact us at support.ecommerce@dpd.fr.
 *
 * @author    DPD France S.A.S. <support.ecommerce@dpd.fr>
 * @copyright 2025 DPD France S.A.S.
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 *}

<script>
    // Les variables shopContext, shopGroupId et shopId sont conditionnées afin d'éviter un conflit avec celles des templates (from_return.tpl & config.tpl)
    // En effet, cela est dû au fait de pouvoir définir 2 configurations différentes pour le module (avec la mise à jour auto des statuts et liens de suivi ou sans)
    let dpdfrance_cron = '{$dpdfrance_cron|escape:'javascript':'UTF-8'}';

    if (typeof shopContext === 'undefined') {
        var shopContext = '{$shop_context|escape:'javascript':'UTF-8'}';
    }
    if (typeof shopGroupId === 'undefined') {
        var shopGroupId = '{$shop_group_id|escape:'javascript':'UTF-8'}';
    }
    if (typeof shopId === 'undefined') {
        var shopId = '{$shop_id|escape:'javascript':'UTF-8'}';
    }

    $.ajax(dpdfrance_cron,
        {
            type: 'GET',
            dataType: 'json',
            data: {
                'shop_context': shopContext,
                'shop_group_id': shopGroupId,
                'shop_id': shopId,
            }
        }
    );
</script>
